"""add availability timeoff rules

Revision ID: a8033d4db57e
Revises: 79bde751258e
Create Date: 2025-12-29 18:32:54.321129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8033d4db57e'
down_revision: Union[str, Sequence[str], None] = '79bde751258e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_availability',
    sa.Column('availability_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('type', sa.Enum('available', 'preferred', name='availability_type'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('availability_id')
    )
    op.create_index(op.f('ix_employee_availability_employee_id'), 'employee_availability', ['employee_id'], unique=False)
    op.create_table('employee_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_start', sa.Date(), nullable=True),
    sa.Column('effective_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index(op.f('ix_employee_rules_employee_id'), 'employee_rules', ['employee_id'], unique=False)
    op.create_table('employee_time_off',
    sa.Column('time_off_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time_off_id')
    )
    op.create_index(op.f('ix_employee_time_off_employee_id'), 'employee_time_off', ['employee_id'], unique=False)
    op.create_table('employee_unavailability',
    sa.Column('unavailability_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unavailability_id')
    )
    op.create_index(op.f('ix_employee_unavailability_employee_id'), 'employee_unavailability', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_unavailability_employee_id'), table_name='employee_unavailability')
    op.drop_table('employee_unavailability')
    op.drop_index(op.f('ix_employee_time_off_employee_id'), table_name='employee_time_off')
    op.drop_table('employee_time_off')
    op.drop_index(op.f('ix_employee_rules_employee_id'), table_name='employee_rules')
    op.drop_table('employee_rules')
    op.drop_index(op.f('ix_employee_availability_employee_id'), table_name='employee_availability')
    op.drop_table('employee_availability')
    # ### end Alembic commands ###
