"""add company logo url

Revision ID: c0c4dcc27def
Revises: a8033d4db57e
Create Date: 2026-01-02 16:35:49.139591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c4dcc27def'
down_revision: Union[str, Sequence[str], None] = 'a8033d4db57e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('logo_url', sa.String(), nullable=True))
    op.drop_index(op.f('uq_employees_company_email'), table_name='employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_employees_company_email'), 'employees', ['company_id', sa.literal_column('lower(email::text)')], unique=True)
    op.drop_column('companies', 'logo_url')
    # ### end Alembic commands ###
